Update macos.yml

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -53,7 +53,7 @@ jobs:
           eval $(opam env)
           brew link postgresql@15
           eval $(opam env)
-          make build-deps || echo failed 
+          #make build-deps || echo failed 
           eval $(opam env)
 
           # zstd
@@ -65,8 +65,8 @@ jobs:
           export PKG_CONFIG_PATH=$(pwd)/zstd-local/lib/pkgconfig
           export PKG_CONFIG="pkg-config --static"
           rm -rf zstd-local/lib/*.dylib
-          export LDFLAGS="-L/Users/runner/work/tezos-macos-pipeline/tezos-macos-pipeline/tezos/zstd-local/lib -Wl,-force_load,/Users/runner/work/tezos-macos-pipeline/tezos-macos-pipeline/tezos/zstd-local/lib/libzstd.a"
-          export CFLAGS="-I/Users/runner/work/tezos-macos-pipeline/tezos-macos-pipeline/tezos/zstd-local/include"
+          export LDFLAGS="-L/$(pwd)/zstd-local/lib -Wl,-force_load,$(pwd)/zstd-local/lib/libzstd.a"
+          export CFLAGS="-I/$(pwd)/zstd-local/include"
 
           # base
           wget https://github.com/janestreet/base/archive/refs/tags/v0.16.3.tar.gz
